services:
  app:
    build: .
    container_name: modelstore-spring
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY}
      YOOKASSA_PAYOUT_GATEWAY_ID: ${YOOKASSA_PAYOUT_GATEWAY_ID}
      YOOKASSA_PAYOUT_GATEWAY_SECRET_KEY: ${YOOKASSA_PAYOUT_GATEWAY_SECRET_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres:16
    container_name: modelstore-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: modelstore-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - app
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]

volumes:
  db_data:
