spring:
  application:
    name: ModelStore
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5 min
    refreshTokenExpiration: 604800 # 7 days
  cors:
    frontendUrl: ${FRONTEND_URL}
  web:
    resources:
      static-locations: file:uploads/


