spring:
  application:
    name: ModelStore
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5 min
    refreshTokenExpiration: 604800 # 7 days
  cors:
    frontendUrl: ${FRONTEND_URL}
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust:
              ${MAIL_HOST}
user:
  verificationToken:
    durationMinutes: 15
  passwordResetToken:
    durationMinutes: 10
yookassa:
  shop-id: ${YOOKASSA_SHOP_ID}
  secret-key: ${YOOKASSA_SECRET_KEY}

