spring:
  application:
    name: ModelStore
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
