spring:
  application:
    name: ModelStore
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5 min
    refreshTokenExpiration: 604800 # 7 days
  cors:
    frontendUrl: ${FRONTEND_URL}
  web:
    resources:
      static-locations: file:uploads/
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
#          ssl:
#            enable: false
#          trust: smtp.yandex.ru

user:
  verificationToken:
    durationMinutes: 15
  passwordResetToken:
    durationMinutes: 10

yookassa:
  shop-id: ${YOOKASSA_SHOP_ID}
  secret-key: ${YOOKASSA_SECRET_KEY}
  payout-gateway-id: ${YOOKASSA_PAYOUT_GATEWAY_ID}
  payout-gateway-secret-key: ${YOOKASSA_PAYOUT_GATEWAY_SECRET_KEY}

payout:
  commission: 0.05
