create table category (
                          id   bigint generated by default as identity
                              constraint category_pk primary key,
                          name varchar(255) not null
);

create table users (
                       id        bigint generated by default as identity
                           constraint users_pk primary key,
                       username  varchar(255) not null constraint users_pk_2 unique,
                       email     varchar(255) not null constraint users_pk_3 unique,
                       password  varchar(255) not null,
                       role      varchar(20)  not null,
                       createdat date         not null
);

create table products (
                          id           bigint generated by default as identity
                              constraint products_pk primary key,
                          title        varchar(255) not null,
                          description  text,
                          price        numeric      not null,
                          previewimage varchar(255),
                          file         varchar(255) not null,
                          owner_id     bigint not null
                              constraint products_users_id_fk references users,
                          category_id  bigint
                              constraint products_category_id_fk references category,
                          createdat    date         not null
);
